const booksData = [
  {
    title: "Powerless",
    author: { first: "Lauren", last: "Roberts", full: "Lauren Roberts" },
    genres: [
      "Fantasy",
      "Romance",
      "Fantasy Romance",
      "Young Adult",
      "Fiction",
      "Dystiopia",
    ],
    pages: 523,
    rating: 4.35,
    ratings: 33098,
    published: "01/31/2023",
    price: 19.17,
    details:
      "She is the very thing he’s spent his whole life hunting. He is the very thing she’s spent her whole life pretending to be. Only the extraordinary belong in the kingdom of Ilya—the exceptional, the empowered, the Elites.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1672676191i/75513900.jpg",
    trendingBook: true,
  },
  {
    title: "To Kill a Mockingbird",
    author: { first: "Harper", last: "Lee", full: "Harper Lee" },
    genres: [
      "Classics",
      "Fiction",
      "Historical Fiction",
      "School",
      "Literature",
      "Young Adult",
    ],
    pages: 323,
    rating: 4.26,
    ratings: 5903852,
    published: "07/11/1960",
    price: 6.69,
    details:
      'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. "To Kill A Mockingbird" became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.',
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1553383690i/2657.jpg",
    topRated: true,
  },
  {
    title: "The Hunger Games",
    author: { first: "Suzanne", last: "Collins", full: "Suzanne Collins" },
    genres: [
      "Young Adult",
      "Fiction",
      "Fantasy",
      "Dystopia",
      "Science Fiction",
      "Romance",
    ],
    pages: 372,
    rating: 4.33,
    ratings: 8303267,
    published: "09/14/2008",
    price: 19.65,
    details:
      "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1586722975i/2767052.jpg",
  },
  {
    title: "The Help",
    author: { first: "Kathryn", last: "Stockett", full: "Kathryn Stockett" },
    genres: [
      "Fiction",
      "Historical Fiction",
      "Historical",
      "Adult",
      "Adult Fiction",
      "Contemporary",
    ],
    pages: 464,
    rating: 4.47,
    ratings: 2678874,
    published: "02/10/2009",
    price: 8.93,
    details:
      "Twenty-two-year-old Skeeter has just returned home after graduating from Ole Miss. She may have a degree, but it is 1962, Mississippi, and her mother will not be happy till Skeeter has a ring on her finger. Skeeter would normally find solace with her beloved maid Constantine, the woman who raised her, but Constantine has disappeared and no one will tell Skeeter where she has gone.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1622355533i/4667024.jpg",
  },
  {
    title: "The Lovely Bones",
    author: { first: "Alice", last: "Sebold", full: "Alice Sebold" },
    genres: [
      "Fiction",
      "Mystery",
      "Young Adult",
      "Contemporary",
      "Fantasy",
      "Crime",
      "Thriller",
    ],
    pages: 372,
    rating: 3.85,
    ratings: 2310895,
    published: "07/03/2002",
    price: 14.02,
    details:
      "So begins the story of Susie Salmon, who is adjusting to her new home in heaven, a place that is not at all what she expected, even as she is watching life on earth continue without her -- her friends trading rumors about her disappearance, her killer trying to cover his tracks, her grief-stricken family unraveling. Out of unspeakable tragedy and loss, The Lovely Bones succeeds, miraculously, in building a tale filled with hope, humor, suspense, even joy.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1457810586i/12232938.jpg",
  },
  {
    title: "The Book Thief",
    author: { first: "Markus", last: "Zusak", full: "Markus Zusak" },
    genres: [
      "Historical Fiction",
      "Fiction",
      "Young Adult",
      "Historical",
      "Classics",
      "War",
      "World War II",
    ],
    pages: 592,
    rating: 4.39,
    ratings: 2465774,
    published: "03/01/2005",
    price: 10.99,
    details:
      "By her brother's graveside, Liesel's life is changed when she picks up a single object, partially hidden in the snow. It is The Gravedigger's Handbook, left behind there by accident, and it is her first act of book thievery. So begins a love affair with books and words, as Liesel, with the help of her accordian-playing foster father, learns to read. Soon she is stealing books from Nazi book-burnings, the mayor's wife's library, wherever there are books to be found.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1522157426i/19063.jpg",
  },
  {
    title: "Memoirs of a Geisha",
    author: { first: "Arthur", last: "Golden", full: "Arthur Golden" },
    genres: [
      "Fiction",
      "Historical Fiction",
      "Romance",
      "Classics",
      "Historical",
      "Japan",
      "Adult",
    ],
    pages: 503,
    rating: 4.15,
    ratings: 1968178,
    published: "01/01/1997",
    price: 26.01,
    details:
      'In "Memoirs of a Geisha," we enter a world where appearances are paramount; where a girl\'s virginity is auctioned to the highest bidder; where women are trained to beguile the most powerful men; and where love is scorned as illusion. It is a unique and triumphant work of fiction - at once romantic, erotic, suspenseful - and completely unforgettable.',
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1409595968i/929.jpg",
    topRated: true,
  },
  {
    title: "Pride and Prejudice",
    author: { first: "Jane", last: "Austen", full: "Jane Austen" },
    genres: [
      "Classics",
      "Fiction",
      "Romance",
      "Historical Fiction",
      "Literature",
      "Historical",
    ],
    pages: 279,
    rating: 4.28,
    ratings: 4115230,
    published: "01/28/1813",
    price: 4.17,
    details:
      'Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work "her own darling child" and its vivacious heroine, Elizabeth Bennet, "as delightful a creature as ever appeared in print." The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen\'s radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England.',
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320399351i/1885.jpg",
  },
  {
    title: "The Time Traveler's Wife",
    author: {
      first: "Audrey",
      last: "Niffenegger",
      full: "Audrey Niffenegger",
    },
    genres: [
      "Fiction",
      "Romance",
      "Fantasy",
      "Time Travel",
      "Science Fiction",
      "Contemporary",
      "Adult",
    ],
    pages: 537,
    rating: 3.99,
    ratings: 1761351,
    published: "01/01/2003",
    price: 28.0,
    details:
      "This is the extraordinary love story of Clare and Henry, who met when Clare was six and Henry was thirty-six, and were married when Clare was twenty-two and Henry was thirty. Impossible but true, because Henry suffers from a rare condition where his genetic clock periodically resets and he finds himself pulled suddenly into his past or future. In the face of this force they can neither prevent nor control, Henry and Clare's struggle to lead normal lives is both intensely moving and entirely unforgettable.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1380660571i/18619684.jpg",
  },
  {
    title: "The Kite Runner",
    author: { first: "Khaled", last: "Hosseini", full: "Khaled Hosseini" },
    genres: [
      "Fiction",
      "Historical Fiction",
      "Classics",
      "Contemporary",
      "Novels",
      "Historical",
      "Literature",
    ],
    pages: 371,
    rating: 4.31,
    ratings: 3056043,
    published: "05/29/2003",
    price: 13.03,
    details:
      "970s Afghanistan: Twelve-year-old Amir is desperate to win the local kite-fighting tournament and his loyal friend Hassan promises to help him. But neither of the boys can foresee what would happen to Hassan that afternoon, an event that is to shatter their lives. After the Russians invade and the family is forced to flee to America, Amir realises that one day he must return to an Afghanistan under Taliban rule to find the one thing that his new world cannot grant him: redemption.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1579036753i/77203.jpg",
  },
  {
    title: "1984",
    author: { first: "George", last: "Orwell", full: "George Orwell" },
    genres: [
      "Classics",
      "Fiction",
      "Science Fiction",
      "Dystopia",
      "Literature",
      "Politics",
      "Novels",
    ],
    pages: 298,
    rating: 4.19,
    ratings: 4411498,
    published: "06/08/1949",
    price: 9.79,
    details:
      "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmarish vision of a totalitarian, bureaucratic world and one poor stiff's attempt to find individuality. The brilliance of the novel is Orwell's prescience of modern life—the ubiquity of television, the distortion of the language—and his ability to construct such a thorough version of hell. Required reading for students since it was published, it ranks among the most terrifying novels ever written.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1532714506i/40961427.jpg",
    topRated: true,
  },
  {
    title: "The Diary of a Young Girl",
    author: { first: "Anne", last: "Frank", full: "Anne Frank" },
    genres: [
      "Classics",
      "Nonfiction",
      "Biography",
      "Memoir",
      "Historical",
      "Holocaust",
      "Autobiography",
    ],
    pages: 283,
    rating: 4.19,
    ratings: 3610762,
    published: "01/01/1947",
    price: 14.89,
    details:
      "In 1942, with the Nazis occupying Holland, a thirteen-year-old Jewish girl and her family fled their home in Amsterdam and went into hiding. For the next two years, until their whereabouts were betrayed to the Gestapo, the Franks and another family lived cloistered in the “Secret Annexe” of an old office building. Cut off from the outside world, they faced hunger, boredom, the constant cruelties of living in confined quarters, and the ever-present threat of discovery and death. In her diary Anne Frank recorded vivid impressions of her experiences during this period. By turns thoughtful, moving, and surprisingly humorous, her account offers a fascinating commentary on human courage and frailty and a compelling self-portrait of a sensitive and spirited young woman whose promise was tragically cut short.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1560816565i/48855.jpg",
    topRated: true,
  },
  {
    title: "A Story of Yesterday",
    author: { first: "Sergio", last: "Cobo", full: "Sergio Cobo" },
    genres: [
      "Thriller",
      "Spanish Literature",
      "European Literature",
      "Mystery",
      "Fiction",
      "Magical Realism",
      "Drama",
    ],
    pages: 70,
    rating: 4.59,
    ratings: 12157,
    published: "03/06/2014",
    price: 13.99,
    details:
      "Under a sky of different colors germinates a magical story of survival, where the result of each choice, enclosed in this particular tale, will snatch the whereabouts of each story forever.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1630609122i/58913358.jpg",
  },
  {
    title: "Little Women",
    author: {
      first: "Luisa",
      last: "Alcott",
      full: "Luisa M. Alcott",
    },
    genres: [
      "Classics",
      "Fiction",
      "Historical Fiction",
      "Young Adult",
      "Romance",
      "Historical",
      "Literature",
    ],
    pages: 449,
    rating: 4.15,
    ratings: 2160093,
    published: "01/01/1868",
    price: 8.97,
    details:
      'Generations of readers young and old, male and female, have fallen in love with the March sisters of Louisa May Alcott’s most popular and enduring novel, Little Women. Here are talented tomboy and author-to-be Jo, tragically frail Beth, beautiful Meg, and romantic, spoiled Amy, united in their devotion to each other and their struggles to survive in New England during the Civil War. It is no secret that Alcott based Little Women on her own early life. While her father, the freethinking reformer and abolitionist Bronson Alcott, hobnobbed with such eminent male authors as Emerson, Thoreau, and Hawthorne, Louisa supported herself and her sisters with "woman’s work,” including sewing, doing laundry, and acting as a domestic servant. But she soon discovered she could make more money writing. Little Women brought her lasting fame and fortune, and far from being the "girl’s book” her publisher requested, it explores such timeless themes as love and death, war and peace, the conflict between personal ambition and family responsibilities, and the clash of cultures between Europe and America.',
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1562690475i/1934.jpg",
  },
  {
    title: "Gone with the Wind",
    author: { first: "Margaret", last: "Mitchell", full: "Margaret Mitchell" },
    genres: [
      "Classics",
      "Historical Fiction",
      "Fiction",
      "Romance",
      "Historical",
      "Literature",
      "War",
    ],
    pages: 1037,
    rating: 4.31,
    ratings: 1195415,
    published: "06/30/1936",
    price: 39.98,
    details:
      "Scarlett O'Hara, the beautiful, spoiled daughter of a well-to-do Georgia plantation owner, must use every means at her disposal to claw her way out of the poverty she finds herself in after Sherman's March to the Sea.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1551144577i/18405.jpg",
    topRated: true,
  },
  {
    title: "Water for Elephants",
    author: { first: "Sara", last: "Gruen", full: "Sara Gruen" },
    genres: [
      "Fiction",
      "Historical Fiction",
      "Romance",
      "Historical",
      "Adult",
      "Adult Fiction",
      "Contemporary",
    ],
    pages: 368,
    rating: 4.11,
    ratings: 1586702,
    published: "03/22/2006",
    price: 23.93,
    details:
      "When Jacob Jankowski, recently orphaned and suddenly adrift, jumps onto a passing train, he enters a world of freaks, drifters, and misfits, a second-rate circus struggling to survive during the Great Depression, making one-night stands in town after endless town. A veterinary student who almost earned his degree, Jacob is put in charge of caring for the circus menagerie. It is there that he meets Marlena, the beautiful young star of the equestrian act, who is married to August, the charismatic but twisted animal trainer. He also meets Rosie, an elephant who seems untrainable until he discovers a way to reach her.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1667708346i/43641.jpg",
  },
  {
    title: "The Eden Paradox (The Eden Paradox vol. 1)",
    author: { first: "Barry", last: "Kirwan", full: "Barry Kirwan" },
    genres: [
      "Science Fiction",
      "Fiction",
      "Space Opera",
      "Dystopia",
      "Space",
      "Contemporary",
      "Drama",
    ],
    pages: 392,
    rating: 4.23,
    ratings: 11707,
    published: "02/16/2011",
    price: 8.99,
    details:
      "In 2063, Earth's overheated climate and war-ravaged cities are near breaking point. A new habitable planet is discovered within reach, but the first two missions have failed to return. This is the story of the third mission to Eden. What really awaits the crew of four as they make the long journey to this supposed uninhabited virgin planet, and what is the link to the secret 900 year old sect known as Alicians back on Earth? While Blake leads the Eden mission, a young researcher named Micah discovers a terrible truth that threatens the very existence of humanity.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1548629676i/43722869.jpg",
  },
  {
    title: "The Girl with the Dragon Tattoo",
    author: { first: "Stieg", last: "Larsson", full: "Stieg Larsson" },
    genres: [
      "Fiction",
      "Mystery",
      "Thriller",
      "Crime",
      "Mystery Thriller",
      "Suspense",
      "Contemporary",
    ],
    pages: 480,
    rating: 4.16,
    ratings: 3108733,
    published: "08/01/2005",
    price: 10.61,
    details:
      "Harriet Vanger, a scion of one of Sweden’s wealthiest families disappeared over forty years ago. All these years later, her aged uncle continues to seek the truth. He hires Mikael Blomkvist, a crusading journalist recently trapped by a libel conviction, to investigate. He is aided by the pierced and tattooed punk prodigy Lisbeth Salander. Together they tap into a vein of unfathomable iniquity and astonishing corruption.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1684638853i/2429135.jpg",
  },
  {
    title: "Jane Eyre",
    author: { first: "Charlotte", last: "Brontë", full: "Charlotte Brontë" },
    genres: [
      "Fiction",
      "Romance",
      "Historical Fiction",
      "Gothic",
      "Literature",
      "Historical",
      "School",
    ],
    pages: 532,
    rating: 4.15,
    ratings: 2043114,
    published: "10/16/1847",
    price: 4.17,
    details:
      "Charlotte Brontë tells the story of orphaned Jane Eyre, who grows up in the home of her heartless aunt, enduring loneliness and cruelty. This troubled childhood strengthens Jane's natural independence and spirit - which prove necessary when she finds employment as a governess to the young ward of Byronic, brooding Mr Rochester. As her feelings for Rochester develop, Jane gradually uncovers Thornfield Hall's terrible secret, forcing her to make a choice. Should she stay with Rochester and live with the consequences, or follow her convictions - even if it means leaving the man she loves? A novel of intense power and intrigue, Jane Eyre dazzled readers with its passionate depiction of a woman's search for equality and freedom.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1557343311i/10210.jpg",
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: { first: "J.K.", last: "Rowling", full: "J.K. Rowling" },
    genres: [
      "Fiction",
      "Young Adult",
      "Magic",
      "Childrens",
      "Middle Grade",
      "Classics",
    ],
    pages: 223,
    rating: 4.47,
    ratings: 9663735,
    published: "06/26/1997",
    price: 13.89,
    details:
      "Harry Potter thinks he is an ordinary boy - until he is rescued by an owl, taken to Hogwarts School of Witchcraft and Wizardry, learns to play Quidditch and does battle in a deadly duel. The Reason ... HARRY POTTER IS A WIZARD!",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    topRated: true,
  },
  {
    title: "Fourth Wing",
    author: { first: "Rebecca", last: "Yarros", full: "Rebecca Yarros" },
    genres: [
      "Fantasy",
      "Romance",
      "Dragons",
      "Fiction",
      "Fantasy Romance",
      "New Adult",
    ],
    pages: 500,
    rating: 4.63,
    ratings: 135491,
    published: "05/02/2023",
    price: 16.99,
    details:
      "Twenty-year-old Violet Sorrengail was supposed to enter the Scribe Quadrant, living a quiet life among books and history. Now, the commanding general—also known as her tough-as-talons mother—has ordered Violet to join the hundreds of candidates striving to become the elite of Navarre: dragon riders.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1701980900i/61431922.jpg",
    trendingBook: true,
  },
  {
    title: "Divine Rivals",
    author: { first: "Rebecca", last: "Ross", full: "Rebecca Ross" },
    genres: [
      "Fantasy",
      "Romance",
      "Young Adult",
      "Fantasy Romance",
      "Historical Fiction",
      "Fiction",
    ],
    pages: 357,
    rating: 4.26,
    ratings: 167600,
    published: "04/04/2023",
    price: 9.49,
    details:
      "After centuries of sleep, the gods are warring again. But eighteen-year-old Iris Winnow just wants to hold her family together. Her mother is suffering from addiction and her brother is missing from the front lines. Her best bet is to win the columnist promotion at the Oath Gazette.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1655928079i/60784546.jpg",
    trendingBook: true,
  },
  {
    title: "The Wishing Game",
    author: { first: "Meg", last: "Shaffer", full: "Meg Shaffer" },
    genres: [
      "Fiction",
      "Fantasy",
      "Romance",
      "Contemporary",
      "Magical Realism",
      "Books About Books",
      "Myster",
    ],
    pages: 304,
    rating: 4.2,
    ratings: 58309,
    published: "05/30/2023",
    price: 21.04,
    details:
      "Lucy Hart knows better than anyone what it’s like to grow up without parents who loved her. In a childhood marked by neglect and loneliness, Lucy found her solace in books, namely the Clock Island series by Jack Masterson. Now a twenty-six-year-old teacher’s aide, she is able to share her love of reading with bright, young students, especially seven-year-old Christopher Lamb, who was left orphaned after the tragic death of his parents. Lucy would give anything to adopt Christopher, but even the idea of becoming a family seems like an impossible dream without proper funds and stability.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1684817680i/62926992.jpg",
    trendingBook: true,
  },
  {
    title: "The Seven Year Slip",
    author: { first: "Ashley", last: "Poston", full: "Ashley Poston" },
    genres: [
      "Romance",
      "Contemporary",
      "Fiction",
      "Time Travel",
      "Magical Realism",
      "Fantasy",
      "Contemporary Romance",
    ],
    pages: 352,
    rating: 4.3,
    ratings: 54200,
    published: "06/27/2023",
    price: 10.99,
    details:
      "So Clementine forms a plan to keep her heart safe: stay busy, work hard, find someone decent to love, and try to remember to chase the moon. The last one is silly and obviously metaphorical, but her aunt always told her that you needed at least one big dream to keep going. And for the last year, that plan has gone off without a hitch. Mostly. The love part is hard because she doesn’t want to get too close to anyone—she isn’t sure her heart can take it.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1685350807i/62926938.jpg",
    trendingBook: true,
  },
  {
    title: "Yellowface",
    author: { first: "R.F.", last: "Kuang", full: "R.F. Kuang" },
    genres: [
      "Ficion",
      "Contemporary",
      "Literary Fiction",
      "Thriller",
      "Adult",
      "Mystery",
    ],
    pages: 336,
    rating: 3.87,
    ratings: 234435,
    published: "05/25/2023",
    price: 14.99,
    details:
      "When Athena dies in a freak accident, June steals her unpublished manuscript and publishes it as her own under the ambiguous name Juniper Song.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1671336608i/62047984.jpg",
    trendingBook: true,
  },
  {
    title: "The Ballad of Songbirds and Snakes",
    author: { first: "Suzanne", last: "Collins", full: "Suzanne Collins" },
    genres: [
      "Young Adult",
      "Dystopia",
      "Fiction",
      "Fantasy",
      "Science Fiction",
      "Romance",
    ],
    pages: 541,
    rating: 3.91,
    ratings: 75323,
    published: "05/19/2020",
    price: 10.99,
    details:
      "It is the morning of the reaping that will kick off the tenth annual Hunger Games. In the Capital, eighteen-year-old Coriolanus Snow is preparing for his one shot at glory as a mentor in the Games. The once-mighty house of Snow has fallen on hard times, its fate hanging on the slender chance that Coriolanus will be able to outcharm, outwit, and outmaneuver his fellow students to mentor the winning tribute.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1593892032i/51901147.jpg",
    trendingBook: true,
  },
  {
    title: "The Heaven & Earth Grocery Store",
    author: { first: "James", last: "McBride", full: "James McBride" },
    genres: [
      "Fiction",
      "Historical Fiction",
      "Literary Fiction",
      "Mystery",
      "Historical",
      "African American",
    ],
    pages: 385,
    rating: 4.25,
    ratings: 34089,
    published: "08/09/2023",
    price: 14.4,
    details:
      "In 1972, when workers in Pottstown, Pennsylvania, were digging the foundations for a new development, the last thing they expected to find was a skeleton at the bottom of a well. Who the skeleton was and how it got there were two of the long-held secrets kept by the residents of Chicken Hill, the dilapidated neighbourhood where immigrant Jews and African Americans lived side by side and shared ambitions and sorrows.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1685350945i/65678550.jpg",
    trendingBook: true,
  },
  {
    title: "None of This Is True",
    author: { first: "Lisa", last: "Jewell", full: "Lisa Jewell" },
    genres: [
      "Thriller",
      "Mystery",
      "Fiction",
      "Mystery Thriller",
      "Suspense",
      "Crime",
    ],
    pages: 384,
    rating: 4.18,
    ratings: 197334,
    published: "07/20/2023",
    price: 15.0,
    details:
      "Celebrating her forty-fifth birthday at her local pub, popular podcaster Alix Summers crosses paths with an unassuming woman called Josie Fair. Josie, it turns out, is also celebrating her forty-fifth birthday. They are, in fact, birthday twins.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1686092508i/62334530.jpg",
    trendingBook: true,
  },
  {
    title: "Tom Lake",
    author: { first: "Ann", last: "Patchett", full: "Anne Patchett" },
    genres: [
      "Fiction",
      "Literary Fiction",
      "Historical Fiction",
      "Romance",
      "Contemporary",
      "Family",
    ],
    pages: 309,
    rating: 4.14,
    ratings: 15068,
    published: "08/01/2023",
    price: 10.12,
    details:
      "This is a story about Peter Duke who went on to be a famous actor. This is a story about falling in love with Peter Duke who wasn't famous at all. It's about falling so wildly in love with him – the way one will at twenty-four – that it felt like jumping off a roof at midnight. There was no way to foresee the mess it would come to in the end.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1691084837i/63241104.jpg",
    trendingBook: true,
  },
  {
    title: "Love, Theoretically",
    author: { first: "Ali", last: "Hazelwood", full: "Ali Hazelwood" },
    genres: [
      "Romance",
      "Contemporary",
      "Contemporary Romance",
      "Fiction",
      "Adult",
      "Chick Lit",
    ],
    pages: 389,
    rating: 4.16,
    ratings: 35981,
    published: "06/13/2023",
    price: 12.64,
    details:
      "The many lives of theoretical physicist Elsie Hannaway have finally caught up with her. By day, she’s an adjunct professor, toiling away at grading labs and teaching thermodynamics in the hopes of landing tenure. By other day, Elsie makes up for her non-existent paycheck by offering her services as a fake girlfriend, tapping into her expertly honed people pleasing skills to embody whichever version of herself the client needs.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1681476644i/61326735.jpg",
    trendingBook: true,
  },
  {
    title: "Hello Beautiful",
    author: { first: "Ann", last: "Napolitano", full: "Ann Napolitano" },
    genres: [
      "Fiction",
      "Historical Fiction",
      "Contemporary",
      "Literary Fiction",
      "Romance",
      "Family",
    ],
    pages: 416,
    rating: 4.2,
    ratings: 18520,
    published: "02/14/2023",
    price: 14.99,
    details:
      "William Waters grew up in a house silenced by tragedy, where his parents could hardly bear to look at him, much less love him. So it’s a relief when his skill on the basketball court earns him a scholarship to college, far away from his childhood home. He soon meets Julia Padavano, a spirited and ambitious young woman who surprises William with her appreciation of his quiet steadiness. With Julia comes her family; she is inseparable from her three younger sisters: Sylvie, the dreamer, is happiest with her nose in a book and imagines a future different from the expected path of wife and mother; Cecelia, the family’s artist; and Emeline, who patiently takes care of all of them. Happily, the Padavanos fold Julia’s new boyfriend into their loving, chaotic household.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1687803098i/61771675.jpg",
    trendingBook: true,
  },
  {
    title: "Happy Place",
    author: { first: "Emily", last: "Henry", full: "Emily Henry" },
    genres: [
      "Romance",
      "Fiction",
      "Contemporary",
      "Adult",
      "Contemporary Romance",
      "Chick Lit",
    ],
    pages: 400,
    rating: 4.06,
    ratings: 74229,
    published: "04/25/2023",
    price: 14.07,
    details:
      "Harriet and Wyn have been the perfect couple since they met in college—they go together like salt and pepper, honey and tea, lobster and rolls. Except, now—for reasons they’re still not discussing—they don’t.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1660145160i/61718053.jpg",
    trendingBook: true,
  },
  {
    title: "A Court of Thorns and Roses",
    author: { first: "Sarah J.", last: "Maas", full: "Sarah J. Maas" },
    genres: [
      "Fantasy",
      "Romance",
      "Young Adult",
      "Fiction",
      "New Adult",
      "Fae",
      "Fantasy Romance",
    ],
    pages: 419,
    rating: 4.2,
    ratings: 1974950,
    published: "05/05/2015",
    price: 4.86,
    details:
      "When nineteen-year-old huntress Feyre kills a wolf in the woods, a terrifying creature arrives to demand retribution. Dragged to a treacherous magical land she knows about only from legends, Feyre discovers that her captor is not truly a beast, but one of the lethal, immortal faeries who once ruled her world.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1620324329i/50659467.jpg",
    trendingBook: true,
  },
  {
    title: "The Bee Sting",
    author: { first: "Paul", last: "Murray", full: "Paul Murray" },
    genres: [
      "Fiction",
      "Ireland",
      "Contemporary",
      "Literary Fiction",
      "Irish Literature",
      "Novels",
      "Family",
    ],
    pages: 656,
    rating: 4.07,
    ratings: 7365,
    published: "08/15/2023",
    price: 29.0,
    details:
      "The Barnes family is in trouble. Dickie’s once-lucrative car business is going under―but rather than face the music, he’s spending his days in the woods, building an apocalypse-proof bunker with a renegade handyman. His wife Imelda is selling off her jewelry on eBay, while their teenage daughter Cass, formerly top of her class, seems determined to binge-drink her way through her final exams. And twelve-year-old PJ is putting the final touches to his grand plan to run away from home.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1674502938i/62039166.jpg",
    trendingBook: true,
  },
  {
    title: "Throne of Glass",
    author: { first: "Sarah J.", last: "Maas", full: "Sarah J. Maas" },
    genres: [
      "Fantasy",
      "Young Adult",
      "Romance",
      "Fiction",
      "Magic",
      "Young Adult Fantasy",
      "High Fantasy",
    ],
    pages: 406,
    rating: 4.19,
    ratings: 1240261,
    published: "08/07/2012",
    price: 19.76,
    details:
      "In a land without magic, where the king rules with an iron hand, an assassin is summoned to the castle. She comes not to kill the king, but to win her freedom. If she defeats twenty-three killers, thieves, and warriors in a competition, she is released from prison to serve as the king's champion. Her name is Celaena Sardothien.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1673566495i/76703559.jpg",
    trendingBook: true,
  },
  {
    title: "Emily Wilde's Encyclopedia of Faeries",
    author: { first: "Heather", last: "Fawcett", full: "Heather Fawcett" },
    genres: [
      "Fantasy",
      "Romance",
      "Fiction",
      "Historical Fiction",
      "Adult",
      "Fae",
      "Historical",
    ],
    pages: 325,
    rating: 4.07,
    ratings: 45893,
    published: "01/10/2023",
    price: 13.98,
    details:
      "Cambridge professor Emily Wilde is good at many things: She is the foremost expert on the study of faeries. She is a genius scholar and a meticulous researcher who is writing the world's first encyclopaedia of faerie lore. But Emily Wilde is not good at people. She could never make small talk at a party--or even get invited to one. And she prefers the company of her books, her dog, and the Fair Folk.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1651622856i/60657589.jpg",
    trendingBook: true,
  },
  {
    title: "Check & Mate",
    author: { first: "Ali", last: "Hazelwood", full: "Ali Hazelwood" },
    genres: [
      "Romance",
      "Young Adult",
      "Contemporary",
      "Fiction",
      "Contemporary Romance",
      "New Adult",
    ],
    pages: 352,
    rating: 4.07,
    ratings: 47823,
    published: "11/07/2023",
    price: 6.99,
    details:
      'Mallory Greenleaf is done with chess. Every move counts nowadays; after the sport led to the destruction of her family four years earlier, Mallory\'s focus is on her mom, her sisters, and the dead-end job that keeps the lights on. That is, until she begrudgingly agrees to play in one last charity tournament and inadvertently wipes the board with notorious "Kingkiller" Nolan Sawyer: current world champion and reigning Bad Boy of chess.',
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1678378842i/60683957.jpg",
    trendingBook: true,
  },
  {
    title: "Icebreaker",
    author: { first: "Hannah", last: "Grace", full: "Hannah Grace" },
    genres: [
      "Romance",
      "Sports Romance",
      "Sports",
      "Contemporary",
      "Hockey",
      "Contemporary Romance",
      "New Adult",
    ],
    pages: 435,
    rating: 3.98,
    ratings: 482764,
    published: "08/23/2022",
    price: 8.95,
    details:
      "A competitive figure skater since she was five years old, a full college scholarship thanks to her place on the Maple Hills skating team, and a schedule that would make even the most driven person weep, Stassie comes to win.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1659045816i/61767292.jpg",
    trendingBook: true,
  },
  {
    title: "The Echo of Old Books",
    author: { first: "Barbara", last: "Davis", full: "Barbara Davis" },
    genres: [
      "Historical Fiction",
      "Fiction",
      "Romance",
      "Mystery",
      "Books About Books",
      "Fantasy",
      "Magical Realism",
    ],
    pages: 431,
    rating: 4.34,
    ratings: 42786,
    published: "05/28/2023",
    price: 4.99,
    details:
      "Rare-book dealer Ashlyn Greer’s affinity for books extends beyond the intoxicating scent of old paper, ink, and leather. She can feel the echoes of the books’ previous owners—an emotional fingerprint only she can read. When Ashlyn discovers a pair of beautifully bound volumes that appear to have never been published, her gift quickly becomes an obsession. Not only is each inscribed with a startling incrimination, but the authors, Hemi and Belle, tell conflicting sides of a tragic romance.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1671274907i/62060274.jpg",
    trendingBook: true,
  },
  {
    title: "Tress of the Emerald Sea",
    author: { first: "Brandon", last: "Sanderson", full: "Brandon Sanderson" },
    genres: [
      "Fantasy",
      "Fiction",
      "Romance",
      "Adventure",
      "Young Adult",
      "High Fantasy",
      "Adult",
    ],
    pages: 483,
    rating: 4.47,
    ratings: 80553,
    published: "01/10/2023",
    price: 19.95,
    details:
      "The only life Tress has known on her island home in an emerald-green ocean has been a simple one, with the simple pleasures of collecting cups brought by sailors from faraway lands and listening to stories told by her friend Charlie. But when his father takes him on a voyage to find a bride and disaster strikes, Tress must stow away on a ship and seek the Sorceress of the deadly Midnight Sea. Amid the spore oceans where pirates abound, can Tress leave her simple life behind and make her own place sailing a sea where a single drop of water can mean instant death?",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1672574587i/60531406.jpg",
    trendingBook: true,
  },
  {
    title: "The Housemaid's Secret",
    author: { first: "Freida", last: "McFadden", full: "Freida McFadden" },
    genres: [
      "Thriller",
      "Mystery",
      "Mystery Thriller",
      "Fiction",
      "Suspense",
      "Psychological Thriller",
    ],
    pages: 318,
    rating: 4.28,
    ratings: 309507,
    published: "02/10/2023",
    price: 7.0,
    details:
      "It's hard to find an employer who doesn't ask too many questions about my past. So I thank my lucky stars that the Garricks miraculously give me a job, cleaning their stunning penthouse with views across the city and preparing fancy meals in their shiny kitchen. I can work here for a while, stay quiet until I get what I want.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1664729357i/62848145.jpg",
    trendingBook: true,
  },
  {
    title: "Assistant to the Villain",
    author: {
      first: "Hannah Nicole",
      last: "Maehrer",
      full: "Hannah Nicole Maehrer",
    },
    genres: [
      "Fantasy",
      "Romance",
      "Fiction",
      "Fantasy Romance",
      "Adult",
      "Magic",
    ],
    pages: 342,
    rating: 3.94,
    ratings: 46253,
    published: "08/29/2023",
    price: 4.32,
    details:
      "ASSISTANT WANTED: Notorious, high-ranking villain seeks loyal, levelheaded assistant for unspecified office duties, supporting staff for random mayhem, terror, and other Dark Things In General. Discretion a must. Excellent benefits.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1702057336i/123257687.jpg",
    trendingBook: true,
  },
  {
    title: "Weyward",
    author: { first: "Emilia", last: "Hart", full: "Emilia Hart" },
    genres: [
      "Historical Fiction",
      "Fantasy",
      "Fiction",
      "Magical Realism",
      "Historical",
      "Witches",
    ],
    pages: 329,
    rating: 4.12,
    ratings: 78351,
    published: "02/02/2023",
    price: 11.44,
    details:
      "Weaving together the stories of three extraordinary women across five centuries, Emilia Hart's Weyward is an enthralling novel of female resilience and the transformative power of the natural world.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1677756582i/60654349.jpg",
    trendingBook: true,
  },
  {
    title: "Good Material",
    author: { first: "Dolly", last: "Alderton", full: "Dolly Alderton" },
    genres: [
      "Fiction",
      "Contemporary",
      "Romance",
      "Literary Fiction",
      "Adult",
      "Adult Fiction",
    ],
    pages: 320,
    rating: 4.24,
    ratings: 8163,
    published: "11/07/2023",
    price: 28.0,
    details:
      "Andy's story wasn't meant to turn out this way. Living out of a suitcase in his best friends' spare room, waiting for his career as a stand-up comedian to finally take off, he struggles to process the life-ruining end of his relationship with the only woman he's ever truly loved.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1694494047i/96177629.jpg",
    trendingBook: true,
  },
  {
    title: "The Great Gatsby",
    author: {
      first: "F. Scott",
      last: "Fitzgerald",
      full: "F. Scott Fitzgerald",
    },
    genres: [
      "Classics",
      "Fiction",
      "School",
      "Historical Fiction",
      "Romance",
      "Literature",
      "Novels",
    ],
    pages: 180,
    rating: 3.93,
    ratings: 5037945,
    published: "01/01/1925",
    price: 11.99,
    details:
      'The Great Gatsby, F. Scott Fitzgerald\'s third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "gin was the national drink and sex the national obsession," it is an exquisitely crafted tale of America in the 1920s.',
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1490528560i/4671.jpg",
    topRated: true,
  },
  {
    title: "Animal Farm",
    author: { first: "George", last: "Orwell", full: "George Orwell" },
    genres: [
      "Classics",
      "Fiction",
      "Dystopia",
      "Fantasy",
      "School",
      "Politics",
      "Literature",
    ],
    pages: 128,
    rating: 3.98,
    ratings: 3789769,
    published: "08/17/1945",
    price: 5.37,
    details:
      "A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned –a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1325861570i/170448.jpg",
    topRated: true,
  },
  {
    title: "The Hobbit",
    author: { first: "J.R.R.", last: "Tolkien", full: "J.R.R. Tolkien" },
    genres: [
      "Fantasy",
      "Classics",
      "Fiction",
      "Adventure",
      "Young Adult",
      "High Fantasy",
      "Science Fiction Fantasy",
    ],
    pages: 366,
    rating: 4.29,
    ratings: 3825110,
    published: "09/21/1937",
    price: 12.99,
    details:
      "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546071216i/5907.jpg",
    topRated: true,
  },
  {
    title: "The Little Prince",
    author: {
      first: "Antoine",
      last: "de Saint-Exupéry",
      full: "Antoine de Saint-Exupéry",
    },
    genres: [
      "Children's",
      "Classics",
      "Adventure",
      "Philosophy",
      "Fantasy",
      "Romance",
      "Literary Fiction",
    ],
    pages: 96,
    rating: 4.3,
    ratings: 1196214,
    published: "04/06/1943",
    price: 9.99,
    details:
      "A timeless tale of innocence and the magic of life. The Little Prince tells the story of a young prince who travels from planet to planet, meeting different inhabitants and learning valuable life lessons.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1367545443i/157993.jpg",
    topRated: true,
  },
  {
    title: "Fahrenheit 451",
    author: { first: "Ray", last: "Bradbury", full: "Ray Bradbury" },
    genres: [
      "Science Fiction",
      "Dystopian",
      "Classics",
      "Fiction",
      "Philosophy",
      "Social Criticism",
      "Cultural",
    ],
    pages: 249,
    rating: 3.98,
    ratings: 1707131,
    published: "10/19/1953",
    price: 14.99,
    details:
      "A classic dystopian novel that explores the consequences of a society that bans books and promotes superficiality.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1383718290i/13079982.jpg",
    topRated: true,
  },
  {
    title: "The Catcher in the Rye",
    author: { first: "J.D.", last: "Salinger", full: "J.D. Salinger" },
    genres: [
      "Classics",
      "Fiction",
      "Coming-of-Age",
      "Literary Fiction",
      "Philosophy",
      "Mental Health",
      "Social Issues",
    ],
    pages: 277,
    rating: 3.81,
    ratings: 2827844,
    published: "07/16/1951",
    price: 10.99,
    details:
      "A novel about teenage alienation and rebellion in society, following the experiences of Holden Caulfield.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1398034300i/5107.jpg",
    topRated: true,
  },
  {
    title: "The Lion, the Witch and the Wardrobe",
    author: { first: "C.S.", last: "Lewis", full: "C.S. Lewis" },
    genres: [
      "Fantasy",
      "Classics",
      "Children's",
      "Adventure",
      "Christian Fiction",
      "Magic Realism",
      "Friendship",
    ],
    pages: 206,
    rating: 4.22,
    ratings: 2189823,
    published: "10/16/1950",
    price: 8.99,
    details:
      "The first book in The Chronicles of Narnia series, depicting the adventures of four siblings in the magical land of Narnia.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1353029077i/100915.jpg",
    topRated: true,
  },
  {
    title: "The Grapes of Wrath",
    author: { first: "John", last: "Steinbeck", full: "John Steinbeck" },
    genres: [
      "Classics",
      "Fiction",
      "Historical Fiction",
      "Social Issues",
      "American Literature",
      "Family",
      "Drama",
    ],
    pages: 464,
    rating: 3.96,
    ratings: 746163,
    published: "04/14/1939",
    price: 11.99,
    details:
      "A powerful novel about the struggles of a family during the Great Depression as they travel to California in search of a better life.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1375670575i/18114322.jpg",
    topRated: true,
  },
  {
    title: "One Hundred Years of Solitude",
    author: {
      first: "Gabriel",
      last: "García Márquez",
      full: "Gabriel García Márquez",
    },
    genres: [
      "Magical Realism",
      "Fiction",
      "Classics",
      "Latin American Literature",
      "Family Saga",
      "Historical Fiction",
      "Fantasy",
    ],
    pages: 417,
    rating: 4.1,
    ratings: 778161,
    published: "05/30/1967",
    price: 13.99,
    details:
      "A landmark novel in the magical realism genre, telling the multi-generational story of the Buendía family in the fictional town of Macondo.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327881361i/320.jpg",
    topRated: true,
  },
  {
    title: "Brave New World",
    author: { first: "Aldous", last: "Huxley", full: "Aldous Huxley" },
    genres: [
      "Dystopian",
      "Science Fiction",
      "Classics",
      "Philosophy",
      "Social Criticism",
      "Fiction",
      "Psychological Fiction",
    ],
    pages: 288,
    rating: 3.98,
    ratings: 1520779,
    published: "01/19/1932",
    price: 12.49,
    details:
      "A dystopian novel that explores a future society where people are engineered for specific roles and controlled through pleasure and conformity.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1575509280i/5129.jpg",
    topRated: true,
  },
  {
    title: "Of Mice and Men",
    author: { first: "John", last: "Steinbeck", full: "John Steinbeck" },
    genres: [
      "Classics",
      "Fiction",
      "Literary Fiction",
      "American Literature",
      "Social Issues",
      "Friendship",
      "Tragedy",
    ],
    pages: 112,
    rating: 3.86,
    ratings: 1868181,
    published: "04/07/1937",
    price: 9.99,
    details:
      "A novella exploring the complex relationships and dreams of two displaced ranch workers during the Great Depression.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1511302904i/890.jpg",
    topRated: true,
  },
  {
    title: "The Giver",
    author: { first: "Lois", last: "Lowry", full: "Lois Lowry" },
    genres: [
      "Dystopian",
      "Young Adult",
      "Science Fiction",
      "Fiction",
      "Philosophy",
      "Social Issues",
      "Coming-of-Age",
    ],
    pages: 208,
    rating: 4.13,
    ratings: 1667594,
    published: "04/26/1993",
    price: 10.99,
    details:
      "A young adult dystopian novel that follows a boy named Jonas as he discovers the dark truths about his seemingly perfect society.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1342493368i/3636.jpg",
    topRated: true,
  },
  {
    title: "Lord of the Flies",
    author: { first: "William", last: "Golding", full: "William Golding" },
    genres: [
      "Classics",
      "Fiction",
      "Adventure",
      "Psychological Fiction",
      "Allegory",
      "Survival",
      "Dystopian",
    ],
    pages: 182,
    rating: 3.68,
    ratings: 2081011,
    published: "09/17/1954",
    price: 11.99,
    details:
      "A classic novel depicting the descent into chaos of a group of boys stranded on an uninhabited island.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327869409i/7624.jpg",
    topRated: true,
  },
  {
    title: "Slaughterhouse-Five",
    author: { first: "Kurt", last: "Vonnegut", full: "Kurt Vonnegut" },
    genres: [
      "Science Fiction",
      "Fiction",
      "Satire",
      "War",
      "Anti-War",
      "Historical Fiction",
      "Metafiction",
    ],
    pages: 275,
    rating: 4.08,
    ratings: 1223529,
    published: "03/31/1969",
    price: 12.99,
    details:
      "A satirical novel that explores the experiences of a soldier, Billy Pilgrim, during and after World War II, including time travel and alien abductions.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1440319389i/4981.jpg",
    topRated: true,
  },
  {
    title: "Lolita",
    author: { first: "Vladimir", last: "Nabokov", full: "Vladimir Nabokov" },
    genres: [
      "Fiction",
      "Classics",
      "Literary Fiction",
      "Controversial",
      "Psychological Fiction",
      "Romance",
      "Dark Humor",
    ],
    pages: 331,
    rating: 3.89,
    ratings: 737566,
    published: "09/15/1955",
    price: 15.99,
    details:
      "A controversial novel that explores the obsession and relationship between a middle-aged literature professor and a twelve-year-old girl.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1377756377i/7604.jpg",
    topRated: true,
  },
  {
    title: "East of Eden",
    author: { first: "John", last: "Steinbeck", full: "John Steinbeck" },
    genres: [
      "Classics",
      "Fiction",
      "Historical Fiction",
      "Family Saga",
      "Literary Fiction",
      "Tragedy",
      "Philosophical",
    ],
    pages: 601,
    rating: 4.38,
    ratings: 416282,
    published: "09/19/1952",
    price: 14.99,
    details:
      "A multi-generational family saga set in California's Salinas Valley, exploring themes of good and evil, and the struggle for identity and acceptance.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1639969375i/4406.jpg",
    topRated: true,
  },
  {
    title: "The Handmaid's Tale",
    author: { first: "Margaret", last: "Atwood", full: "Margaret Atwood" },
    genres: [
      "Dystopian",
      "Fiction",
      "Science Fiction",
      "Feminism",
      "Political",
      "Social Issues",
      "Speculative Fiction",
    ],
    pages: 311,
    rating: 4.1,
    ratings: 1061092,
    published: "02/17/1986",
    price: 13.49,
    details:
      "A dystopian novel that explores a society where women's rights have been severely restricted, and fertility is a precious commodity.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1578028274i/38447.jpg",
    topRated: true,
  },
  {
    title: "The Fellowship of the Ring",
    author: { first: "J.R.R.", last: "Tolkien", full: "J.R.R. Tolkien" },
    genres: [
      "Fantasy",
      "Classics",
      "Adventure",
      "High Fantasy",
      "Epic Fantasy",
      "Magic",
      "Quest",
    ],
    pages: 398,
    rating: 4.36,
    ratings: 2357025,
    published: "07/29/1954",
    price: 16.99,
    details:
      "The first volume of J.R.R. Tolkien's epic fantasy trilogy, The Lord of the Rings, following the quest to destroy the One Ring.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1298411339i/34.jpg",
    topRated: true,
  },
  {
    title: "One Flew Over the Cuckoo's Nest",
    author: { first: "Ken", last: "Kesey", full: "Ken Kesey" },
    genres: [
      "Classics",
      "Fiction",
      "Psychological Fiction",
      "Mental Health",
      "Social Issues",
      "Rebellion",
      "Satire",
    ],
    pages: 325,
    rating: 4.23,
    ratings: 927813,
    published: "02/01/1962",
    price: 12.99,
    details:
      "A novel set in a mental institution, narrated by a patient, that explores the dehumanizing effects of institutionalization and the power struggle between the staff and patients.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1516211014i/332613.jpg",
    topRated: true,
  },
  {
    title: "The Stranger",
    author: { first: "Albert", last: "Camus", full: "Albert Camus" },
    genres: [
      "Classics",
      "Fiction",
      "Philosophical",
      "Existentialism",
      "Absurdist",
      "Literary Fiction",
      "Crime",
    ],
    pages: 123,
    rating: 3.98,
    ratings: 790556,
    published: "05/07/1942",
    price: 9.99,
    details:
      "A novel that explores the sense of alienation and existentialism through the story of an emotionally detached and indifferent protagonist.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1590930002i/49552.jpg",
    topRated: true,
  },
  {
    title: "The Ultimate Hitchhiker's Guide to the Galaxy",
    author: { first: "Douglas", last: "Adams", full: "Douglas Adams" },
    genres: [
      "Science Fiction",
      "Humor",
      "Fiction",
      "Satire",
      "Fantasy",
      "Adventure",
      "British Literature",
    ],
    pages: 815,
    rating: 4.38,
    ratings: 270569,
    published: "11/12/1986",
    price: 14.99,
    details:
      "A comedic science fiction series that follows the misadventures of an unwitting human, Arthur Dent, and his alien friend Ford Prefect as they travel through space.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1404613595i/13.jpg",
    topRated: true,
  },
  {
    title: "Charlotte's Web",
    author: { first: "E.B.", last: "White", full: "E.B. White" },
    genres: [
      "Children's",
      "Classics",
      "Fiction",
      "Animals",
      "Friendship",
      "Family",
      "Fantasy",
    ],
    pages: 184,
    rating: 4.18,
    ratings: 1578943,
    published: "10/15/1952",
    price: 8.99,
    details:
      "A beloved children's novel that tells the story of a pig named Wilbur and his friendship with a spider named Charlotte, who saves him from being slaughtered.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1628267712i/24178.jpg",
    topRated: true,
  },
  {
    title: "A Wrinkle in Time",
    author: { first: "Madeleine", last: "L'Engle", full: "Madeleine L'Engle" },
    genres: [
      "Science Fiction",
      "Fantasy",
      "Young Adult",
      "Adventure",
      "Time Travel",
      "Classic Literature",
      "Family",
    ],
    pages: 211,
    rating: 4.02,
    ratings: 884874,
    published: "01/01/1962",
    price: 11.99,
    details:
      "A science fantasy novel that follows the adventures of Meg Murry, her brother Charles Wallace, and their friend Calvin O'Keefe as they journey through space and time.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1507963312i/33574273.jpg",
    topRated: true,
  },
  {
    title: "The Old Man and the Sea",
    author: { first: "Ernest", last: "Hemingway", full: "Ernest Hemingway" },
    genres: [
      "Classics",
      "Fiction",
      "Adventure",
      "Literary Fiction",
      "Sea Stories",
      "Hemingwayesque",
      "Novella",
    ],
    pages: 127,
    rating: 3.77,
    ratings: 771727,
    published: "09/01/1952",
    price: 9.99,
    details:
      "A novella that tells the story of an aging Cuban fisherman, Santiago, and his epic battle with a giant marlin in the Gulf Stream.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1329189714i/2165.jpg",
    topRated: true,
  },
  {
    title: "Ender's Game",
    author: { first: "Orson", last: "Scott Card", full: "Orson Scott Card" },
    genres: [
      "Science Fiction",
      "Fiction",
      "Military Science Fiction",
      "Young Adult",
      "Dystopian",
      "Space Opera",
      "Coming-of-Age",
    ],
    pages: 324,
    rating: 4.31,
    ratings: 1266937,
    published: "01/01/1985",
    price: 12.99,
    details:
      'A military science fiction novel that follows the story of Andrew "Ender" Wiggin, a young prodigy, as he trains at a space military school to fight in an interstellar war.',
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1408303130i/375802.jpg",
    topRated: true,
  },
  {
    title: "The Giving Tree",
    author: { first: "Shel", last: "Silverstein", full: "Shel Silverstein" },
    genres: [
      "Children's",
      "Picture Books",
      "Fiction",
      "Philosophy",
      "Friendship",
      "Allegory",
      "Nature",
    ],
    pages: 64,
    rating: 4.39,
    ratings: 982745,
    published: "10/07/1964",
    price: 13.99,
    details:
      "A classic children's book that tells the story of the relationship between a boy and a tree, illustrating the concept of selfless love and giving.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1174210942i/370493.jpg",
    topRated: true,
  },
  {
    title: "The Return of the King",
    author: { first: "J.R.R.", last: "Tolkien", full: "J.R.R. Tolkien" },
    genres: [
      "Fantasy",
      "Classics",
      "Adventure",
      "High Fantasy",
      "Epic Fantasy",
      "Magic",
      "Quest",
    ],
    pages: 490,
    rating: 4.53,
    ratings: 666172,
    published: "10/20/1955",
    price: 15.99,
    details:
      "The third volume of J.R.R. Tolkien's epic fantasy trilogy, The Lord of the Rings, bringing the story to its epic conclusion.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1574117762i/838729.jpg",
    topRated: true,
  },
  {
    title: "Night",
    author: { first: "Elie", last: "Wiesel", full: "Elie Wiesel" },
    genres: [
      "Memoir",
      "Autobiography",
      "Nonfiction",
      "History",
      "Holocaust",
      "War",
      "Jewish",
    ],
    pages: 120,
    rating: 4.33,
    ratings: 1049060,
    published: "01/01/1956",
    price: 10.99,
    details:
      "A memoir detailing Elie Wiesel's experiences as a teenager in the Nazi concentration camps Auschwitz and Buchenwald during the Holocaust.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1575073611i/1617.jpg",
    topRated: true,
  },
  {
    title: "A Tree Grows in Brooklyn",
    author: { first: "Betty", last: "Smith", full: "Betty Smith" },
    genres: [
      "Classics",
      "Fiction",
      "Coming-of-Age",
      "Historical Fiction",
      "Family",
      "Urban",
      "Literary Fiction",
    ],
    pages: 493,
    rating: 4.26,
    ratings: 369337,
    published: "09/01/1943",
    price: 12.99,
    details:
      "A coming-of-age novel that follows the life of Francie Nolan, a young girl growing up in the Williamsburg neighborhood of Brooklyn.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327883484i/14891.jpg",
    topRated: true,
  },
  {
    title: "The Bell Jar",
    author: { first: "Sylvia", last: "Plath", full: "Sylvia Plath" },
    genres: [
      "Classics",
      "Fiction",
      "Autobiography",
      "Mental Health",
      "Feminism",
      "Literary Fiction",
      "Psychology",
    ],
    pages: 244,
    rating: 4.05,
    ratings: 649725,
    published: "01/14/1963",
    price: 11.99,
    details:
      "A semi-autobiographical novel that explores the mental health struggles of Esther Greenwood, a young woman in the 1950s.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554582218i/6514.jpg",
    topRated: true,
  },
  {
    title: "Watership Down",
    author: { first: "Richard", last: "Adams", full: "Richard Adams" },
    genres: [
      "Fiction",
      "Adventure",
      "Fantasy",
      "Animals",
      "Classic Literature",
      "Nature",
      "Epic",
    ],
    pages: 478,
    rating: 4.06,
    ratings: 383089,
    published: "11/01/1972",
    price: 13.99,
    details:
      "An epic fantasy novel that follows a group of rabbits as they escape the destruction of their warren and seek a new home.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1405136931i/76620.jpg",
    topRated: true,
  },
  {
    title: "The Alchemist",
    author: { first: "Paulo", last: "Coelho", full: "Paulo Coelho" },
    genres: [
      "Fiction",
      "Philosophical",
      "Spirituality",
      "Adventure",
      "Fantasy",
      "Magical Realism",
      "Self Help",
    ],
    pages: 163,
    rating: 3.86,
    ratings: 2033852,
    published: "01/01/1988",
    price: 14.99,
    details:
      "A philosophical novel that follows the journey of Santiago, a shepherd, as he seeks a hidden treasure in the Egyptian pyramids.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1654371463i/18144590.jpg",
    topRated: true,
  },
  {
    title: "Into Thin Air: A Personal Account of the Mount Everest Disaster",
    author: { first: "Jon", last: "Krakauer", full: "Jon Krakauer" },
    genres: [
      "Nonfiction",
      "Adventure",
      "Mountaineering",
      "Survival",
      "Biography",
      "Travel",
      "True Story",
    ],
    pages: 368,
    rating: 4.15,
    ratings: 394820,
    published: "04/22/1997",
    price: 14.99,
    details:
      "A gripping firsthand account of the 1996 Mount Everest disaster, where eight climbers lost their lives during a storm while attempting to reach the summit.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1631501298i/1898.jpg",
  },
  {
    title: "Into the Wild",
    author: { first: "Jon", last: "Krakauer", full: "Jon Krakauer" },
    genres: [
      "Nonfiction",
      "Adventure",
      "Biography",
      "Travel",
      "Nature",
      "Survival",
      "True Story",
    ],
    pages: 207,
    rating: 4.06,
    ratings: 805009,
    published: "01/13/1996",
    price: 12.99,
    details:
      "A biographical account of Christopher McCandless, a young man who left society to live in the Alaskan wilderness and tragically died there.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1634587789i/1845.jpg",
  },
  {
    title:
      "Freakonomics: A Rogue Economist Explores the Hidden Side of Everything",
    author: { first: "Steven D.", last: "Levitt", full: "Steven D. Levitt" },
    genres: [
      "Nonfiction",
      "Economics",
      "Popular Science",
      "Social Sciences",
      "Business",
      "Behavioral Economics",
      "Statistics",
    ],
    pages: 320,
    rating: 3.98,
    ratings: 688496,
    published: "05/01/2005",
    price: 11.99,
    details:
      "A book that applies economic principles to diverse topics, uncovering unexpected connections and revealing the hidden forces at play in various aspects of life.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1550917827i/1202.jpg",
  },
  {
    title: "A Short History of Nearly Everything",
    author: { first: "Bill", last: "Bryson", full: "Bill Bryson" },
    genres: [
      "Nonfiction",
      "Science",
      "History",
      "Popular Science",
      "Physics",
      "Geology",
      "Cosmology",
    ],
    pages: 544,
    rating: 4.2,
    ratings: 248801,
    published: "05/06/2003",
    price: 15.99,
    details:
      "An exploration of various scientific topics, providing an accessible and engaging overview of the history of the universe, Earth, and life.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1433086293i/21.jpg",
  },
  {
    title: "The Glass Castle",
    author: { first: "Jeannette", last: "Walls", full: "Jeannette Walls" },
    genres: [
      "Memoir",
      "Nonfiction",
      "Autobiography",
      "Family",
      "Biography",
      "Poverty",
      "Coming-of-Age",
    ],
    pages: 288,
    rating: 4.27,
    ratings: 870619,
    published: "01/17/2005",
    price: 13.99,
    details:
      "A memoir depicting the author's unconventional and challenging childhood, growing up in a dysfunctional but ultimately resilient family.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1523542886i/7445.jpg",
  },
  {
    title: "In Cold Blood",
    author: { first: "Truman", last: "Capote", full: "Truman Capote" },
    genres: [
      "True Crime",
      "Nonfiction",
      "Crime",
      "Journalism",
      "Mystery",
      "American Literature",
      "Investigative Journalism",
    ],
    pages: 343,
    rating: 4.07,
    ratings: 512549,
    published: "01/17/1966",
    price: 14.99,
    details:
      "A true crime novel that recounts the brutal murders of the Clutter family in Kansas in 1959 and the investigation and trial that followed.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1424931136i/168642.jpg",
  },
  {
    title: "Under the Banner of Heaven: A Story of Violent Faith",
    author: { first: "Jon", last: "Krakauer", full: "Jon Krakauer" },
    genres: [
      "Nonfiction",
      "True Crime",
      "Religion",
      "History",
      "Mormonism",
      "Cultural",
      "Investigative Journalism",
    ],
    pages: 399,
    rating: 4.05,
    ratings: 139328,
    published: "07/15/2003",
    price: 13.99,
    details:
      "An investigative look into the history of the Mormon Church, focusing on a double murder committed by brothers who claimed to be following a divine revelation.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1356441391i/10847.jpg",
  },
  {
    title: "Angela's Ashes",
    author: { first: "Frank", last: "McCourt", full: "Frank McCourt" },
    genres: [
      "Memoir",
      "Nonfiction",
      "Autobiography",
      "Irish Literature",
      "Coming-of-Age",
      "Family",
      "Poverty",
    ],
    pages: 364,
    rating: 4.1,
    ratings: 531546,
    published: "05/25/1996",
    price: 12.99,
    details:
      "A memoir that recounts the author's impoverished childhood and early adulthood in Limerick, Ireland.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348317139i/252577.jpg",
  },
  {
    title: "Guns, Germs, and Steel: The Fates of Human Societies",
    author: { first: "Jared", last: "Diamond", full: "Jared Diamond" },
    genres: [
      "Nonfiction",
      "History",
      "Science",
      "Anthropology",
      "Sociology",
      "Geography",
      "Cultural Studies",
    ],
    pages: 425,
    rating: 4.03,
    ratings: 239642,
    published: "03/01/1997",
    price: 14.99,
    details:
      "A comprehensive exploration of human history, examining the factors that led to the dominance of certain societies over others.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1453215833i/1842.jpg",
  },
  {
    title:
      "The Devil in the White City: Murder, Magic, and Madness at the Fair That Changed America",
    author: { first: "Erik", last: "Larson", full: "Erik Larson" },
    genres: [
      "Nonfiction",
      "History",
      "True Crime",
      "Architecture",
      "Chicago",
      "Biography",
      "American History",
    ],
    pages: 447,
    rating: 3.99,
    ratings: 446387,
    published: "02/10/2003",
    price: 13.99,
    details:
      "A dual narrative that intertwines the story of the 1893 Chicago World's Fair and the activities of the serial killer H.H. Holmes.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1583433024i/397483.jpg",
  },
  {
    title: "Outliers: The Story of Success",
    author: { first: "Malcolm", last: "Gladwell", full: "Malcolm Gladwell" },
    genres: [
      "Nonfiction",
      "Psychology",
      "Sociology",
      "Success",
      "Business",
      "Self-Help",
      "Popular Science",
    ],
    pages: 309,
    rating: 4.15,
    ratings: 1417780,
    published: "11/18/2008",
    price: 12.99,
    details:
      "An exploration of the factors that contribute to high levels of success, questioning the traditional notions of individual achievement.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1344266315i/3228917.jpg",
  },
  {
    title: "The Tipping Point: How Little Things Can Make a Big Difference",
    author: { first: "Malcolm", last: "Gladwell", full: "Malcolm Gladwell" },
    genres: [
      "Nonfiction",
      "Psychology",
      "Sociology",
      "Marketing",
      "Social Sciences",
      "Business",
      "Popular Science",
    ],
    pages: 301,
    rating: 3.97,
    ratings: 702842,
    published: "01/07/2000",
    price: 11.99,
    details:
      'An exploration of the phenomenon of the "tipping point" and how small changes can lead to significant shifts in behavior and trends.',
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1473396980i/2612.jpg",
  },
  {
    title: "The Omnivore's Dilemma: A Natural History of Four Meals",
    author: { first: "Michael", last: "Pollan", full: "Michael Pollan" },
    genres: [
      "Nonfiction",
      "Food",
      "Science",
      "Agriculture",
      "Environment",
      "Sustainability",
      "Nutrition",
    ],
    pages: 450,
    rating: 4.18,
    ratings: 203394,
    published: "04/11/2006",
    price: 15.99,
    details:
      "An exploration of the food industry and the various ways in which food is produced, examining the ethical and environmental implications.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1393804353i/3109.jpg",
  },
  {
    title: "Eat, Pray, Love",
    author: { first: "Elizabeth", last: "Gilbert", full: "Elizabeth Gilbert" },
    genres: [
      "Memoir",
      "Nonfiction",
      "Travel",
      "Spirituality",
      "Self-Discovery",
      "Autobiography",
      "Relationships",
    ],
    pages: 334,
    rating: 3.55,
    ratings: 1500190,
    published: "02/16/2006",
    price: 14.99,
    details:
      "A memoir chronicling the author's journey of self-discovery as she travels to Italy, India, and Indonesia in search of balance and fulfillment.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1503066414i/19501.jpg",
  },
  {
    title: "A Brief History of Time",
    author: { first: "Stephen", last: "Hawking", full: "Stephen Hawking" },
    genres: [
      "Nonfiction",
      "Science",
      "Physics",
      "Cosmology",
      "Astrophysics",
      "Philosophy",
      "Quantum Mechanics",
    ],
    pages: 212,
    rating: 4.18,
    ratings: 262046,
    published: "04/01/1988",
    price: 14.99,
    details:
      "A bestselling exploration of complex scientific concepts, written by renowned physicist Stephen Hawking, covering topics like time, space, and the nature of the universe.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1333578746i/3869.jpg",
  },
  {
    title: "Cosmos",
    author: { first: "Carl", last: "Sagan", full: "Carl Sagan" },
    genres: [
      "Nonfiction",
      "Science",
      "Cosmology",
      "Astronomy",
      "Astrophysics",
      "Space",
      "Philosophy",
    ],
    pages: 384,
    rating: 4.37,
    ratings: 155605,
    published: "10/01/1980",
    price: 15.99,
    details:
      "A classic exploration of the universe, combining science, philosophy, and history, written by astronomer and science communicator Carl Sagan.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388620656i/55030.jpg",
  },
  {
    title: "The Selfish Gene",
    author: { first: "Richard", last: "Dawkins", full: "Richard Dawkins" },
    genres: [
      "Nonfiction",
      "Science",
      "Biology",
      "Evolution",
      "Genetics",
      "Natural Selection",
      "Philosophy",
    ],
    pages: 360,
    rating: 4.12,
    ratings: 140135,
    published: "06/01/1976",
    price: 14.99,
    details:
      "A groundbreaking work on evolutionary biology, exploring the concept of the gene as a central unit of natural selection.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1366758096i/61535.jpg",
  },
  {
    title: "The Demon-Haunted World: Science as a Candle in the Dark",
    author: { first: "Carl", last: "Sagan", full: "Carl Sagan" },
    genres: [
      "Nonfiction",
      "Science",
      "Skepticism",
      "Critical Thinking",
      "Astronomy",
      "Philosophy",
      "Social Commentary",
    ],
    pages: 457,
    rating: 4.3,
    ratings: 65721,
    published: "02/25/1997",
    price: 13.99,
    details:
      "A passionate defense of scientific thinking and skepticism, encouraging a reliance on evidence and reason in the face of superstition and pseudoscience.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1553691804i/17349.jpg",
  },
  {
    title:
      "Surely You're Joking, Mr. Feynman!: Adventures of a Curious Character",
    author: {
      first: "Richard P.",
      last: "Feynman",
      full: "Richard P. Feynman",
    },
    genres: [
      "Nonfiction",
      "Biography",
      "Memoir",
      "Physics",
      "Autobiography",
      "Science",
      "Humor",
    ],
    pages: 350,
    rating: 4.29,
    ratings: 140754,
    published: "02/28/1985",
    price: 12.99,
    details:
      "An entertaining and insightful memoir of Nobel Prize-winning physicist Richard Feynman, recounting his adventures and experiences in a humorous and engaging manner.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1504936953i/35167685.jpg",
  },
  {
    title: "The Origin of Species",
    author: { first: "Charles", last: "Darwin", full: "Charles Darwin" },
    genres: [
      "Nonfiction",
      "Science",
      "Biology",
      "Evolution",
      "Natural Selection",
      "Darwinism",
      "Philosophy",
    ],
    pages: 490,
    rating: 3.99,
    ratings: 209154,
    published: "11/24/1859",
    price: 11.99,
    details:
      "Charles Darwin's groundbreaking work on the theory of evolution, presenting the idea of natural selection as a mechanism for the development of species.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1298417570i/22463.jpg",
  },
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: { first: "Rebecca", last: "Skloot", full: "Rebecca Skloot" },
    genres: [
      "Nonfiction",
      "Science",
      "Biology",
      "Medicine",
      "Medical Ethics",
      "History",
      "Biography",
    ],
    pages: 370,
    rating: 4.05,
    ratings: 547028,
    published: "02/02/2010",
    price: 13.99,
    details:
      "A biography of Henrietta Lacks, whose cells were used without her knowledge to make significant contributions to medical research.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327878144i/6493208.jpg",
  },
  {
    title:
      "The Elegant Universe: Superstrings, Hidden Dimensions, and the Quest for the Ultimate Theory",
    author: { first: "Brian", last: "Greene", full: "Brian Greene" },
    genres: [
      "Nonfiction",
      "Science",
      "Physics",
      "Cosmology",
      "Quantum Mechanics",
      "String Theory",
      "Philosophy",
    ],
    pages: 464,
    rating: 4.06,
    ratings: 77497,
    published: "02/10/1999",
    price: 15.99,
    details:
      "An exploration of modern physics, focusing on string theory and the quest for a unified theory of the fundamental forces of the universe.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348791881i/8049273.jpg",
  },
  {
    title: "Gödel, Escher, Bach: An Eternal Golden Braid",
    author: {
      first: "Douglas R.",
      last: "Hofstadter",
      full: "Douglas R. Hofstadter",
    },
    genres: [
      "Nonfiction",
      "Science",
      "Philosophy",
      "Mathematics",
      "Art",
      "Cognition",
      "Computers",
    ],
    pages: 777,
    rating: 4.29,
    ratings: 39818,
    published: "04/01/1979",
    price: 17.99,
    details:
      "A Pulitzer Prize-winning book that explores the connections between mathematics, art, and music, using the works of Gödel, Escher, and Bach as a starting point.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1547125681i/24113.jpg",
  },
  {
    title: "Thinking, Fast and Slow",
    author: { first: "Daniel", last: "Kahneman", full: "Daniel Kahneman" },
    genres: [
      "Nonfiction",
      "Psychology",
      "Behavioral Economics",
      "Cognitive Psychology",
      "Decision Making",
      "Philosophy",
      "Science",
    ],
    pages: 499,
    rating: 4.14,
    ratings: 458347,
    published: "10/25/2011",
    price: 14.99,
    details:
      "A comprehensive exploration of the two systems of thought that drive human decision-making, written by Nobel Prize-winning psychologist Daniel Kahneman.",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1317793965i/11468377.jpg",
  },
];

booksData.forEach((book) => {
  book.id = `${book.title[0]}${book.author.first[0]}${book.author.last[0]}-${book.pages}-${book.title[1]}${book.title[0]}`;
});

function shuffle(array) {
  let currentIndex = array.length,
    randomIndex;

  // While there remain elements to shuffle.
  while (currentIndex > 0) {
    // Pick a remaining element.
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    // And swap it with the current element.
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex],
      array[currentIndex],
    ];
  }

  return array;
}
shuffle(booksData);

booksData.slice(0, 20).forEach((book) => (book.isDiscounted = true));
booksData.forEach((book) => {
  if (book.isDiscounted) {
    book.discountedPrice = (book.price - (book.price / 100) * 25).toFixed(2);
  }
});

shuffle(booksData);
export default booksData;
